openapi: 3.0.0
info: 
  title: Ecommerce api
  description: REST API for a ecomm tshirt store
  version: 0.1.0

servers:
  - url: http://localhost:3000/api/v1

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token

    BearerAuth:
      type: http
      scheme: bearer

paths:
  /dummy:
    get:
      tags:
        - home
      summary: returns a msg.
      description: dummy route for testing
      responses:
        200:
          description: string
          content:
            application/json:
              schema:
                type: string
  
  /signup:
    post:
      tags:
        - user
      summary: returns a object.
      description: returns a new user info.
      consumes:
        - multipart/form-data
      produces:
        - application/json
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                photo:
                  type: string
                  format: binary
      responses:
        200:
          description: returns a object
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
                  token:
                    type: string

  /login:
    post:
      tags:
        - user
      summary: login into account.
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email: 
                  type: string
                password:
                  type: string
      responses:
        200:
          description: returns a object
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      _id:
                        type: string
  
  /logout:
    get:
      tags:
        - user
      summary: user logout
      responses:
        200:
          description: user logs out.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                             